### ISSUE TITLE
Updated midori crashes frequently in ubuntu 14.04

### ISSUE THREAD

**Issue by potholiday** [eustasy/midori-browser.org#74]
I have installed Midori 0.4.6 from ubuntu repo and after testing a while upgraded to the Midori 0.5.10 using the terminal codes described in midori website. After this up-gradation (or degradation) I cant even run midori for 15 minutes. I use multiple tabs to open websites but some how this is causing crashing of the website and If you stream a youtube video midori crashes.  I was looking for an alternative for firefox and chrome (both uses lots of system resources) and found midori but it was a biggest disappointment. 

In ubuntu Midori stable version was uploaded in 2011 which is 4 years back and these unstable versions are really pathethic. Any way I stopped using midori but not uninstalling from my system.

**Comment by lewisgoddard** [comment]
This isn't really the place for support calls for Midori, it's for the development of the Midori-Browser.org website. On that note, you should be better off asking on #midori on IRC.

That said, the 0.5.10 builds aren't unstable in themselves, they are newer, but stable, releases in their own right.  I'm not sure which Ubuntu version you're using, since their site doesn't list any Midori in the repos for 14.04 or later.
